"""create hotels and deals

Revision ID: 0b58f6461c77
Revises:
Create Date: 2026-02-12 00:25:45.480293

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b58f6461c77"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hotels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotels")),
        sa.UniqueConstraint("name", "city", "country", name="uq_hotel_location"),
        sa.UniqueConstraint("phone", name=op.f("uq_hotels_phone")),
    )
    op.create_table(
        "deals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.Integer(), nullable=False),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("room_type", sa.String(length=50), nullable=False),
        sa.Column("price_per_night", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("original_price", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("discount_percent", sa.Integer(), nullable=False),
        sa.Column("checkin_date", sa.Date(), nullable=False),
        sa.Column("checkout_date", sa.Date(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("categories", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "checkin_date <= checkout_date", name=op.f("ck_deals_checkin_before_checkout")
        ),
        sa.CheckConstraint(
            "discount_percent >= 0 AND discount_percent <= 100",
            name=op.f("ck_deals_discount_percent_range"),
        ),
        sa.CheckConstraint(
            "original_price > 0 AND original_price <= 99999",
            name=op.f("ck_deals_original_price_range"),
        ),
        sa.CheckConstraint(
            "price_per_night > 0 AND price_per_night <= 99999",
            name=op.f("ck_deals_price_per_night_range"),
        ),
        sa.CheckConstraint("rating >= 1 AND rating <= 5", name=op.f("ck_deals_rating_range")),
        sa.ForeignKeyConstraint(["hotel_id"], ["hotels.id"], name=op.f("fk_deals_hotel_id_hotels")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deals")),
        sa.UniqueConstraint("external_id", name=op.f("uq_deals_external_id")),
    )
    op.create_index(op.f("ix_deals_hotel_id"), "deals", ["hotel_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deals_hotel_id"), table_name="deals")
    op.drop_table("deals")
    op.drop_table("hotels")
    # ### end Alembic commands ###
